# Generated by Django 5.0.3 on 2024-03-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_name',
            new_name='customer_need',
        ),
    ]
